### PR TITLE
Alarms from local files

### PR DESCRIPTION
**Pull request by quipri**
implements #10 

It seems to work.

I plan to try to implement playlist support as well.

### CODE REVIEW

**Comment by fennifith** [comment]
:o this looks amazing, thank you!

I've been a little inactive recently, but I promise to take some time to look at what you've done, squash some bugs, and get another release out soon!

**Comment by quipri** [comment]
Actually, it looks like there are some issues I have to look into, I guess when you access an audio file you don't necessarily retain the right to do so forever.

**Comment by fennifith** [comment]
Err, yeah, files can move. It doesn't necessarily have to handle the error in any elaborate way, we can just have it fall back to the default ringtone (`PreferenceData.DEFAULT_ALARM_RINGTONE`) - actually, it should do that for the radio as well... I'm not sure if it does :|

We should still have the error handling as above, but this would be less of a problem if the `FileChooserActivity` could return a path to the file _after copying it to Alarmio's data dir_, so that it still has a copy of the file if the original disappears. I believe it's actually stated in the Android docs somewhere that this is what apps should do when using `ACTION_GET_CONTENT` as certain results can be "unstable", e.g. I believe the images returned by Google Photos are just stored in cache. I should've had the activity doing this from the beginning, but I was too lazy when all it was used for was the background image.

**Comment by quipri** [comment]
I'm not sure about files moving, but I'm seeing things I was supposed to do about requesting permanent permission to access the URI that I need to try.

**Pull request merged**
